---
sudo: required
dist: trusty

addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable

language: node_js
node_js:
  - "4"

cache:
  yarn: true
  directories:
    - $HOME/.npm
    - $HOME/.cache

env:
  - EMBER_TRY_SCENARIO=ember-lts-2.4
  - EMBER_TRY_SCENARIO=ember-lts-2.8
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

before_install:
  # Setup for Chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # Other setup
  - npm config set spin false
  - npm install -g bower yarn
  - bower --version

install:
  - yarn install
  - bower install

script:
  # Usually, it's ok to finish the test scenario without reverting
  # to the addon's original dependency state, skipping "cleanup".
  - ember try:one $EMBER_TRY_SCENARIO --skip-cleanup=true --- yarn test
